name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.CI_REGISTRY }}

      - name: Copy environment file
        run: cp $ENV_FILE .env
      
      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.CI_REGISTRY_IMAGE }}/main:${{ github.sha }}" -t "${{ secrets.CI_REGISTRY_IMAGE }}/main:latest" -f ./deployments/main.dockerfile .
      
      - name: Push Docker image
        run: |
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}/main:${{ github.sha }}"
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}/main:latest"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin ${{ secrets.CI_REGISTRY }}

      - name: Pull Docker images
        run: docker compose -f deployments/docker-compose.prod.yml --project-directory ./ pull
      
      - name: Deploy Docker containers
        run: docker compose -f deployments/docker-compose.prod.yml --project-directory ./ up --force-recreate --build --remove-orphans -d
      
      - name: Prune unused Docker images
        run: docker image prune -f
